/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bangumi/': RouteRecordInfo<
      '/bangumi/',
      '/bangumi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/food-map/': RouteRecordInfo<
      '/food-map/',
      '/food-map',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/严重的焦虑与抑郁': RouteRecordInfo<
      '/posts/严重的焦虑与抑郁',
      '/posts/%E4%B8%A5%E9%87%8D%E7%9A%84%E7%84%A6%E8%99%91%E4%B8%8E%E6%8A%91%E9%83%81',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/云南之旅': RouteRecordInfo<
      '/posts/云南之旅',
      '/posts/%E4%BA%91%E5%8D%97%E4%B9%8B%E6%97%85',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/关于性别认同--为何想成为药娘呢': RouteRecordInfo<
      '/posts/关于性别认同--为何想成为药娘呢',
      '/posts/%E5%85%B3%E4%BA%8E%E6%80%A7%E5%88%AB%E8%AE%A4%E5%90%8C--%E4%B8%BA%E4%BD%95%E6%83%B3%E6%88%90%E4%B8%BA%E8%8D%AF%E5%A8%98%E5%91%A2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/决定写一点流水账的日记！': RouteRecordInfo<
      '/posts/决定写一点流水账的日记！',
      '/posts/%E5%86%B3%E5%AE%9A%E5%86%99%E4%B8%80%E7%82%B9%E6%B5%81%E6%B0%B4%E8%B4%A6%E7%9A%84%E6%97%A5%E8%AE%B0%EF%BC%81',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/另世我': RouteRecordInfo<
      '/posts/另世我',
      '/posts/%E5%8F%A6%E4%B8%96%E6%88%91',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/大学第一天——意外的老油条之旅': RouteRecordInfo<
      '/posts/大学第一天——意外的老油条之旅',
      '/posts/%E5%A4%A7%E5%AD%A6%E7%AC%AC%E4%B8%80%E5%A4%A9%E2%80%94%E2%80%94%E6%84%8F%E5%A4%96%E7%9A%84%E8%80%81%E6%B2%B9%E6%9D%A1%E4%B9%8B%E6%97%85',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/孤独群候症': RouteRecordInfo<
      '/posts/孤独群候症',
      '/posts/%E5%AD%A4%E7%8B%AC%E7%BE%A4%E5%80%99%E7%97%87',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/幻梦，死于现实，亦或是软弱': RouteRecordInfo<
      '/posts/幻梦，死于现实，亦或是软弱',
      '/posts/%E5%B9%BB%E6%A2%A6%EF%BC%8C%E6%AD%BB%E4%BA%8E%E7%8E%B0%E5%AE%9E%EF%BC%8C%E4%BA%A6%E6%88%96%E6%98%AF%E8%BD%AF%E5%BC%B1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/怨念': RouteRecordInfo<
      '/posts/怨念',
      '/posts/%E6%80%A8%E5%BF%B5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/意外的多了很多感慨': RouteRecordInfo<
      '/posts/意外的多了很多感慨',
      '/posts/%E6%84%8F%E5%A4%96%E7%9A%84%E5%A4%9A%E4%BA%86%E5%BE%88%E5%A4%9A%E6%84%9F%E6%85%A8',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/无言': RouteRecordInfo<
      '/posts/无言',
      '/posts/%E6%97%A0%E8%A8%80',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/无题': RouteRecordInfo<
      '/posts/无题',
      '/posts/%E6%97%A0%E9%A2%98',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/签签万万': RouteRecordInfo<
      '/posts/签签万万',
      '/posts/%E7%AD%BE%E7%AD%BE%E4%B8%87%E4%B8%87',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/诗（2023）': RouteRecordInfo<
      '/posts/诗（2023）',
      '/posts/%E8%AF%97%EF%BC%882023%EF%BC%89',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/诗（2024）': RouteRecordInfo<
      '/posts/诗（2024）',
      '/posts/%E8%AF%97%EF%BC%882024%EF%BC%89',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/跨年': RouteRecordInfo<
      '/posts/跨年',
      '/posts/%E8%B7%A8%E5%B9%B4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/过去': RouteRecordInfo<
      '/posts/过去',
      '/posts/%E8%BF%87%E5%8E%BB',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2023年终总结以及我个人杂七杂八的事情1': RouteRecordInfo<
      '/posts/2023年终总结以及我个人杂七杂八的事情1',
      '/posts/2023%E5%B9%B4%E7%BB%88%E6%80%BB%E7%BB%93%E4%BB%A5%E5%8F%8A%E6%88%91%E4%B8%AA%E4%BA%BA%E6%9D%82%E4%B8%83%E6%9D%82%E5%85%AB%E7%9A%84%E4%BA%8B%E6%83%851',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/An-SSH-configuration-error-caused-a-failure-during-blog-deployment': RouteRecordInfo<
      '/posts/An-SSH-configuration-error-caused-a-failure-during-blog-deployment',
      '/posts/An-SSH-configuration-error-caused-a-failure-during-blog-deployment',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Debian-Using-WSL2-to-run-Debian': RouteRecordInfo<
      '/posts/Debian-Using-WSL2-to-run-Debian',
      '/posts/Debian-Using-WSL2-to-run-Debian',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/First': RouteRecordInfo<
      '/posts/First',
      '/posts/First',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Free-blog-setup-using-Hexo-and-GitHub': RouteRecordInfo<
      '/posts/Free-blog-setup-using-Hexo-and-GitHub',
      '/posts/Free-blog-setup-using-Hexo-and-GitHub',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Hidden-root-tinkering-notes-for-the-Pixel-7-Pro': RouteRecordInfo<
      '/posts/Hidden-root-tinkering-notes-for-the-Pixel-7-Pro',
      '/posts/Hidden-root-tinkering-notes-for-the-Pixel-7-Pro',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/HRT100days自己的生活发生什么变化了吗1': RouteRecordInfo<
      '/posts/HRT100days自己的生活发生什么变化了吗1',
      '/posts/HRT100days%E8%87%AA%E5%B7%B1%E7%9A%84%E7%94%9F%E6%B4%BB%E5%8F%91%E7%94%9F%E4%BB%80%E4%B9%88%E5%8F%98%E5%8C%96%E4%BA%86%E5%90%971',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Milk-cats-mission-part1': RouteRecordInfo<
      '/posts/Milk-cats-mission-part1',
      '/posts/Milk-cats-mission-part1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Milk-cats-mission-part2': RouteRecordInfo<
      '/posts/Milk-cats-mission-part2',
      '/posts/Milk-cats-mission-part2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/nx30pro-Flashing-the-router-firmware': RouteRecordInfo<
      '/posts/nx30pro-Flashing-the-router-firmware',
      '/posts/nx30pro-Flashing-the-router-firmware',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/YubiKey-Troubleshooting-Notes': RouteRecordInfo<
      '/posts/YubiKey-Troubleshooting-Notes',
      '/posts/YubiKey-Troubleshooting-Notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.27.0_vue@3.5.32_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@0.27.0_@babel+parser@7.29.2_@nuxt+kit@3.21.2_@types+markdown-it@14.1.2_@types+node@25._rslroq7kziv7z3p2bqsirmkujm/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/bangumi/index.md': {
      routes:
        | '/bangumi/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/food-map/index.md': {
      routes:
        | '/food-map/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.27.0_vue@3.5.32_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.27.0_vue@3.5.32_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/严重的焦虑与抑郁.md': {
      routes:
        | '/posts/严重的焦虑与抑郁'
      views:
        | never
    }
    'pages/posts/云南之旅.md': {
      routes:
        | '/posts/云南之旅'
      views:
        | never
    }
    'pages/posts/关于性别认同--为何想成为药娘呢.md': {
      routes:
        | '/posts/关于性别认同--为何想成为药娘呢'
      views:
        | never
    }
    'pages/posts/决定写一点流水账的日记！.md': {
      routes:
        | '/posts/决定写一点流水账的日记！'
      views:
        | never
    }
    'pages/posts/另世我.md': {
      routes:
        | '/posts/另世我'
      views:
        | never
    }
    'pages/posts/大学第一天——意外的老油条之旅.md': {
      routes:
        | '/posts/大学第一天——意外的老油条之旅'
      views:
        | never
    }
    'pages/posts/孤独群候症.md': {
      routes:
        | '/posts/孤独群候症'
      views:
        | never
    }
    'pages/posts/幻梦，死于现实，亦或是软弱.md': {
      routes:
        | '/posts/幻梦，死于现实，亦或是软弱'
      views:
        | never
    }
    'pages/posts/怨念.md': {
      routes:
        | '/posts/怨念'
      views:
        | never
    }
    'pages/posts/意外的多了很多感慨.md': {
      routes:
        | '/posts/意外的多了很多感慨'
      views:
        | never
    }
    'pages/posts/无言.md': {
      routes:
        | '/posts/无言'
      views:
        | never
    }
    'pages/posts/无题.md': {
      routes:
        | '/posts/无题'
      views:
        | never
    }
    'pages/posts/签签万万.md': {
      routes:
        | '/posts/签签万万'
      views:
        | never
    }
    'pages/posts/诗（2023）.md': {
      routes:
        | '/posts/诗（2023）'
      views:
        | never
    }
    'pages/posts/诗（2024）.md': {
      routes:
        | '/posts/诗（2024）'
      views:
        | never
    }
    'pages/posts/跨年.md': {
      routes:
        | '/posts/跨年'
      views:
        | never
    }
    'pages/posts/过去.md': {
      routes:
        | '/posts/过去'
      views:
        | never
    }
    'pages/posts/2023年终总结以及我个人杂七杂八的事情1.md': {
      routes:
        | '/posts/2023年终总结以及我个人杂七杂八的事情1'
      views:
        | never
    }
    'pages/posts/An-SSH-configuration-error-caused-a-failure-during-blog-deployment.md': {
      routes:
        | '/posts/An-SSH-configuration-error-caused-a-failure-during-blog-deployment'
      views:
        | never
    }
    'pages/posts/Debian-Using-WSL2-to-run-Debian.md': {
      routes:
        | '/posts/Debian-Using-WSL2-to-run-Debian'
      views:
        | never
    }
    'pages/posts/First.md': {
      routes:
        | '/posts/First'
      views:
        | never
    }
    'pages/posts/Free-blog-setup-using-Hexo-and-GitHub.md': {
      routes:
        | '/posts/Free-blog-setup-using-Hexo-and-GitHub'
      views:
        | never
    }
    'pages/posts/Hidden-root-tinkering-notes-for-the-Pixel-7-Pro.md': {
      routes:
        | '/posts/Hidden-root-tinkering-notes-for-the-Pixel-7-Pro'
      views:
        | never
    }
    'pages/posts/HRT100days自己的生活发生什么变化了吗1.md': {
      routes:
        | '/posts/HRT100days自己的生活发生什么变化了吗1'
      views:
        | never
    }
    'pages/posts/Milk-cats-mission-part1.md': {
      routes:
        | '/posts/Milk-cats-mission-part1'
      views:
        | never
    }
    'pages/posts/Milk-cats-mission-part2.md': {
      routes:
        | '/posts/Milk-cats-mission-part2'
      views:
        | never
    }
    'pages/posts/nx30pro-Flashing-the-router-firmware.md': {
      routes:
        | '/posts/nx30pro-Flashing-the-router-firmware'
      views:
        | never
    }
    'pages/posts/YubiKey-Troubleshooting-Notes.md': {
      routes:
        | '/posts/YubiKey-Troubleshooting-Notes'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
